# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\pbf\ui\noticeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_noticeDialog(object):
    def setupUi(self, noticeDialog):
        noticeDialog.setObjectName("noticeDialog")
        noticeDialog.resize(400, 300)
        self.textBrowser = QtWidgets.QTextBrowser(noticeDialog)
        self.textBrowser.setGeometry(QtCore.QRect(-1, -1, 401, 301))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(noticeDialog)
        QtCore.QMetaObject.connectSlotsByName(noticeDialog)

    def retranslateUi(self, noticeDialog):
        _translate = QtCore.QCoreApplication.translate
        noticeDialog.setWindowTitle(_translate("noticeDialog", "新公告"))
