# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\pbf\ui\pluginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pluginDialog(object):
    def setupUi(self, pluginDialog):
        pluginDialog.setObjectName("pluginDialog")
        pluginDialog.resize(400, 214)
        pluginDialog.setStyleSheet("")
        self.label = QtWidgets.QLabel(pluginDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(pluginDialog)
        self.groupBox.setGeometry(QtCore.QRect(260, 10, 120, 140))
        self.groupBox.setObjectName("groupBox")
        self.installBtn = QtWidgets.QPushButton(self.groupBox)
        self.installBtn.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.installBtn.setObjectName("installBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.groupBox)
        self.cancelBtn.setGeometry(QtCore.QRect(20, 70, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.openBtn = QtWidgets.QPushButton(self.groupBox)
        self.openBtn.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.openBtn.setObjectName("openBtn")
        self.label_2 = QtWidgets.QLabel(pluginDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(pluginDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(pluginDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(pluginDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 54, 12))
        self.label_5.setObjectName("label_5")
        self.PluginName = QtWidgets.QLabel(pluginDialog)
        self.PluginName.setGeometry(QtCore.QRect(60, 60, 190, 12))
        self.PluginName.setObjectName("PluginName")
        self.PluginVersion = QtWidgets.QLabel(pluginDialog)
        self.PluginVersion.setGeometry(QtCore.QRect(60, 80, 190, 12))
        self.PluginVersion.setObjectName("PluginVersion")
        self.PluginAuthor = QtWidgets.QLabel(pluginDialog)
        self.PluginAuthor.setGeometry(QtCore.QRect(60, 100, 190, 12))
        self.PluginAuthor.setObjectName("PluginAuthor")
        self.PluginDes = QtWidgets.QLabel(pluginDialog)
        self.PluginDes.setGeometry(QtCore.QRect(60, 120, 190, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PluginDes.sizePolicy().hasHeightForWidth())
        self.PluginDes.setSizePolicy(sizePolicy)
        self.PluginDes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.PluginDes.setObjectName("PluginDes")

        self.retranslateUi(pluginDialog)
        QtCore.QMetaObject.connectSlotsByName(pluginDialog)

    def retranslateUi(self, pluginDialog):
        _translate = QtCore.QCoreApplication.translate
        pluginDialog.setWindowTitle(_translate("pluginDialog", "安装插件"))
        self.label.setText(_translate("pluginDialog", "插件详情"))
        self.groupBox.setTitle(_translate("pluginDialog", "操作"))
        self.installBtn.setText(_translate("pluginDialog", "安装/更新"))
        self.cancelBtn.setText(_translate("pluginDialog", "取消"))
        self.openBtn.setText(_translate("pluginDialog", "打开插件"))
        self.label_2.setText(_translate("pluginDialog", "插件名："))
        self.label_3.setText(_translate("pluginDialog", "作者："))
        self.label_4.setText(_translate("pluginDialog", "版本："))
        self.label_5.setText(_translate("pluginDialog", "描述："))
        self.PluginName.setText(_translate("pluginDialog", "TextLabel"))
        self.PluginVersion.setText(_translate("pluginDialog", "TextLabel"))
        self.PluginAuthor.setText(_translate("pluginDialog", "TextLabel"))
        self.PluginDes.setText(_translate("pluginDialog", "TextLabel"))
